export const SET_SEARCH_TERM = "SEARCH::SET_SEARCH_TERM";
export const FETCH_BOOKS_PENDING = "BOOKLIST::FETCH_BOOKS_PENDING";
export const FETCH_BOOKS_SUCCESS = "BOOKLIST::FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_FAILED = "BOOKLIST::FETCH_BOOKS_FAILED";
export const FETCH_CURRENT_BOOK_PENDING =
  "CURRENTBOOK::FETCH_CURRENT_BOOK_PENDING";
export const FETCH_CURRENT_BOOK_SUCCESS =
  "CURRENTBOOK::FETCH_CURRENT_BOOK_SUCCESS";
export const FETCH_CURRENT_BOOK_FAILED =
  "CURRENTBOOK::FETCH_CURRENT_BOOK_FAILED";
export const POST_BOOK_REVIEW_PENDING = "REVIEWFORM::POST_BOOK_REVIEW_PENDING";
export const POST_BOOK_REVIEW_FAILED = "REVIEWFORM::POST_BOOK_REVIEW_FAILED";
export const POST_BOOK_REVIEW_SUCCESS = "REVIEWFORM::POST_BOOK_REVIEW_SUCCESS";
